### ISSUE TITLE
kiss mode is only set for TNC-2 compatible TNCs

### ISSUE THREAD

**Issue by ac2cz** [ac2cz/Falcon#34]
Should we support other methods of entering KISS mode, or should we require the TNC to be left in KISS mode?  Do we need to disable the KISS on/off commands in that case?

**Comment by ac2cz** [comment]
Request to support Kantronics which needs "int kiss"  sent and then a "reset" sent

**Comment by ac2cz** [comment]
Note that "exit" from kiss seems to be more standard.  Which means we might want kiss on/kiss off to be optional for TNC which are not supported

**Comment by ac2cz** [comment]
Paul N8HM suggested a screen like this from UI-View32:
![image](https://user-images.githubusercontent.com/14824793/52817022-9ffae080-3070-11e9-80fc-46b13be6207c.png)

**Comment by ac2cz** [comment]
As a work around I added a setting for "Toggle TNC in/out of KISS".  This allows you to put any TNC into KISS mode outside of the program.

**Comment by sjkps** [comment]
I agree with Paul that a method for additional setup commands would be worthy, for a Kantronics 9612 plus I have found that it is also necessary to set carrier detect to external and monitor to on to work properly

**Comment by ac2cz** [comment]
How do you set those additional parameters?  Is that by sending special bytes?  Would it work with the sort of screen shot that Paul provided?

**Comment by sjkps** [comment]
I start a putty session and issue
maxusers 0/1   
cd external/external  
mon off/on
int  kiss
reset
Then I  exit putty and then I start  pacsat,  all of those are not always needed as it depends on what other programs have been run before, programs do not always put the settings back to the way they found them :) 
And yes Pauls screenshot would be fine.

**Comment by sjkps** [comment]
Thought about this overnight and wanted to suggest, instead of 4 or 5 fields how about a option to load in a txt file? then a person could have as few or as many commands needed to setup their particular TNC?

**Comment by ac2cz** [comment]
Yes, that is perhaps the way to go. Good suggestion.

**Comment by ac2cz** [comment]
This is now fixed in the latest version.  It allows you to send arbitrary bytes at open/close of the program.  You need Version 0.38.8 to test this as there was a bug sending the custom bytes.   It is easiest to download the new jar file and patch the version you have.  Keep the existing jar file and un-patch it if it does not work.  The jar file is here:  https://www.g0kla.com/pacsat/PacSatGround.jar
