### ISSUE TITLE
Have not checked for an hour or more. Requesting dir. --> removal request

### ISSUE THREAD

**Issue by BX2ABT** [ac2cz/Falcon#47]
When leaving PSGS open in the background after a session it will start requesting a directory update after an hour of inactivity. FS-3 will not be around for half an hour then, so this will cause inappropriate use of the upload frequency. The exact text displayed in PSGS is the one in the title.
Otherwise PSGS is working very nicely. No problems at all.

**Comment by ac2cz** [comment]
Definitely a bug. Thanks

**Comment by ac2cz** [comment]
This is in 0.26
