### ISSUE TITLE
The software does not start in W10

### ISSUE THREAD

**Issue by lu4fta** [ac2cz/Falcon#76]
The problem appeared suddenly when I changed the TNC settings. Does not start. I leave the error log. I will appreciate a solution.
Thank you very much and 73 !!
Felipe LU4FTA.
[hs_err_pid7248.log](https://github.com/ac2cz/Falcon/files/5507141/hs_err_pid7248.log)

**Comment by ac2cz** [comment]
Felipe, sorry to take so long to respond.  Try the latest version, v0.38.3.  I am using an update to the library that communicates with the TNC.  Hopefully it fixes the issue.  You can download a new jar file here: https://www.g0kla.com/pacsat/PacSatGround.jar  Replace the jar file in your existing installation.

**Comment by lu4fta** [comment]
Hello Cris Thank you very much for answering my question. I already solved
by downgrading to a previous version of JAVA. Now it works. Glad there is a
new version that connects to TNC. Tonight I'm going to take them down and
try them. Thank you very much and happy Christmas and New Years.
73 de Felipe LU4FTA.

**Comment by ac2cz** [comment]
Yes, the serial library was updated by author so that it works with the latest Java versions.  My website has the updated jar file.  I'm working on some updates to the manual.  If you wait a couple of days there will be a full release.

**Comment by lu4fta** [comment]
Ok, thank you!
