### ISSUE TITLE
Performance Issue - Version 0.37

### ISSUE THREAD

**Issue by LarryPhelps-K4OZS** [ac2cz/Falcon#77]
PacSat Ground start-up time has ballooned from a few seconds to more than a minute.  In addition, each line received from "High-Speed SoundModem" now takes about one second to appear.  This results in about a two minute delay after LOS to finish processing.  As a reference, the computer is i7 990 3GHz with only SatPC32, the SoundModem, and PacSat Ground running.

Deleting everything and re-installing the program restores the original interactive performance.

My question at this point:  Is there a SAFE way to delete some really old files to eliminate the backlog while retaining the directory structure? My attempts to accomplish this were way less than successful.

Thanks.

**Comment by ac2cz** [comment]
Thanks for the report Larry. Is this also an issue with 0.36?  I've had
reports that 0.37 is slower and 0.36 is still fine.

**Comment by LarryPhelps-K4OZS** [comment]
Chris,This behavior actually started with 0.36I tried deleting SOME of the old files as well as the directory to see if simply rebuilding the structure would speed things up. That created a host of problems. At that juncture I just deleted everything and re-installed the program to get going again. It again got slower to load and process as time went on.With 0.37 I have just let it run. It just takes longer and longer to load. The big and ever-increasing delay in processing data seems to me to be causing QRM due to hugely out of sync transmissions. Just a guess on that observation. If there is a way to safely delete old files, that would help maintain lively operation.Thanks for looking into this.73-LarryK4OZSFox-1A, 1B, 1D, and Now Fox-1Cliff: All In Orbit.
-------- Original message --------From: Chris Thompson <notifications@github.com> Date: 12/10/20  1:08 PM  (GMT-05:00) To: ac2cz/Falcon <Falcon@noreply.github.com> Cc: LarryPhelps-K4OZS <k4ozs@embarqmail.com>, Author <author@noreply.github.com> Subject: Re: [ac2cz/Falcon] Performance Issue - Version 0.37 (#77) 

Thanks for the report Larry. Is this also an issue with 0.36?  I've had

reports that 0.37 is slower and 0.36 is still fine.





On Wed, Dec 9, 2020, 16:21 LarryPhelps-K4OZS <notifications@github.com>

wrote:

**Comment by ac2cz** [comment]
Yes, once it slows down the TX/RX loop gets out of sync and that does cause QRM.  Ideally those would not be linked to the size of the directory.  I forget why that gets in the way, but it does.  I have seen it before.

I'll have a look at it and see if there is something I can do.

**Comment by BX2ABT** [comment]
Let me chime in here. Still using 0.36 (didn't realize there was 0.37) 
and I've seen the same thing happening. Been collecting every bit of 
data from the sat since January, so now there are 8900 files in my data 
directory, which totals 150MB. Can log on, but only few packets coming 
back, usually after a number of seconds.

I made a new data directory and that helped, but you lose all your old 
messages in that way, of course. HTH --Hans

P.S. I wanted to ask you about this earlier, but I've got a new HF 
antenna on the roof, so I'm playing with that right now. Sats got put on 
the back burner, I'm afraid.

**Comment by ac2cz** [comment]
I have implemented a new version that addresses this.  It is experimental, but if you want to test it then it is on my website https://www.g0kla.com/pacsat and is V0.38.1

This addresses the problem in two ways
1/ It removes any processing from the core control loops.  A large directory will still slow things down, but it should not slow down the send/receive loop to the spacecraft
2/ It implements an Archive function that will move most of the headers and files to an archive folder.  I need to document that in the manual, but broadly speaking it keeps the most recent headers (specified on the Spacecraft settings screen) and moves the rest to an archive folder (specified on the File > Settings screen.  You run it from File > Archive the directory.

Back up your files before testing this :)

**Comment by LarryPhelps-K4OZS** [comment]
Installed V0.38.2 today.  Archive seems to work OK.  Will watch performance during the next series of passes here.
-------- Original message --------From: Chris Thompson <notifications@github.com> Date: 12/21/20  3:08 PM  (GMT-05:00) To: ac2cz/Falcon <Falcon@noreply.github.com> Cc: LarryPhelps-K4OZS <k4ozs@embarqmail.com>, Author <author@noreply.github.com> Subject: Re: [ac2cz/Falcon] Performance Issue - Version 0.37 (#77) 
I have implemented a new version that addresses this.  It is experimental, but if you want to test it then it is on my website https://www.g0kla.com/pacsat and is V0.38.1
This addresses the problem in two ways
1/ It removes any processing from the core control loops.  A large directory will still slow things down, but it should not slow down the send/receive loop to the spacecraft
2/ It implements an Archive function that will move most of the headers and files to an archive folder.  I need to document that in the manual, but broadly speaking it keeps the most recent headers (specified on the Spacecraft settings screen) and moves the rest to an archive folder (specified on the File > Settings screen.  You run it from File > Archive the directory.
Back up your files before testing this :)

**Comment by ac2cz** [comment]
There is a bug on v0.38.2 that causes repeated DIR requests.  I have an updated version 0.38.3 that fixes the issue.  Can download here: https://www.g0kla.com/pacsat

**Comment by LarryPhelps-K4OZS** [comment]
Loaded v0.38.3 and will continue watching.
Archive feature is really nice.
