### ISSUE TITLE
No connect/download using 38.5

### ISSUE THREAD

**Issue by ALMASSARO** [ac2cz/Falcon#78]
There are 2 of us trying to participate in this with no luck so we are looking for direction.
Both stations are using the latest download available
One station using SDR, soundmodem and beam antenna, listening only at this point.
The other using an ICOM 706MKllG (9600 baud), an MFJ TNC2 (9600 kiss), diamond vertical antenna,
Alternate setup with Soundmodem and signalink
Sat is heard and seen on waterfalls.
Tx file request is working and confirmed by other station @ +-5sec intervals, 706 in split for V/U 
Using TCP connection for soundmodem 8000/8100
Com port ID'd for MFJ TNC

What have we missed? What are we doing wrong?

Any Help appreciated
KF5SMH
AL M

**Comment by ac2cz** [comment]
Thanks for reaching out.  It sounds like you can copy the spacecraft and see the downlink.  When the station transmits a directory request, do you get a response?  You should see something like this printed in the downlink text:
OK KF5SMH
PB: KF5SMH/D

You might miss one of the two packets, but usually you see one of them.  Receiving one of these packets stops the ground station unlinking the DIR request packet.  The ground station then waits to get DIR broadcast packets and until it is no longer on the PB.

If you can't get a response from the spacecraft then you may not be in full duplex mode.  Both the TNC and the radio need to be full duplex.  Split will not work.  If your radio does not support full duplex then you need two radios. An SDR might work for one of the radios but the latency needs to be kept to a minimum.

Let me know if that helps.

**Comment by ALMASSARO** [comment]
Thank you for the prompt response! 
I am going to try an ICOM IC2720 that is full duplex 9600 baud capable, 
Wish me luck!
KF5SMH
AL M

**Comment by ALMASSARO** [comment]
The ICOM 2720 seems to work, but I am not getting any downlink info from the Sat. The other fellow that is working it here is doing better using a TS2000. Guess this Sat not for me. Thanks for the help!
AL M
KF5SMH

**Comment by ALMASSARO** [comment]
Ok so after 10 days of trying various things, the other station is copying the downlink info when it is available, not able to tell which pass will produce successfully from TLEs, just a wait and see game. I am not able to copy anything at all, which makes no sense, but after many changes and different antenna/radio setups, I have come to the conclusion I am not equipped for this Sat. Disappointing to be sure as I truly was anxious to attempt a QSO on it.
Thanks for the help,
AL M
KF5SMH

**Comment by ac2cz** [comment]
Sorry to hear you are not having luck with this.  You do need a decent antenna.  If you don't have a yagi you can point at the sat then it probably won't work.  The 70cm downlink decodes well with a 10 element yagi, but I don't think it will decode with an omni.

I find that a pre-amp makes a huge difference too.  I get solid reception with a 10 element and a mast head pre-amp.  With the pre-amp off then I start to need higher passes.
