### ISSUE TITLE
Error Message when Connecting to UISS

### ISSUE THREAD

**Issue by dougmcco** [ac2cz/Falcon#81]
Hi:

PacSat is working well as a stand alone. 

However, when I set up PacSat TNC to connect to UISS via TNC host 127.0.0.1 and Port 8000 (same on UISS) receive the following error message:

IO Error connecting to the TNC over TCP with host: 127.0.0.1 and port 8000.
Software caused connection abort: socket write error.

Appreciate your thoughts.

73,
Doug WA6RLR

**Comment by ac2cz** [comment]
Doug, did you every get this resolved?  Let me know if I can add an explanation here for others with the same issue.

**Comment by dougmcco** [comment]
Chris:

Not completely.

As you speculated, using the COM port splitter not all the RX/TX packets
show up on UISS and Pacsat.

It appears depending on which program receives a packet first becomes the
primary the other the secondary. But then the programs switch back and
forth from primary to secondary and I cannot tell what is driving what.
That's when packets do not show up on either program, or in the case of
Pacsat it appears the program hangs until I click on the directory button
to re-engage.

The COM Port splitter does work and I have been able to RX/TX via both
programs.

Thoughts?

73,
Doug

**Comment by ac2cz** [comment]
I'm closing this old issue.  I have used UISS along side Pacsat Ground without issue.  The setup I tsted is for UISS to connect to the TNC using TCP and for Pacsat Ground to also connect to the TNC via TCP.  Testing with Direwolf shows that this works.
