### ISSUE TITLE
norad ID needs to be updated for MIR-SAT1

### ISSUE THREAD

**Issue by bal-nbrookes** [ac2cz/Falcon#88]
In the properties for mir-sat1, the norad ID needs to be updated from 99718 to 48868 as well as the address for logging received telemetry data.

**Comment by ac2cz** [comment]
@bal-nbrookes good point.  This should be updated in the default file.  You can of course also change it on the satellite settings window.

**Comment by ac2cz** [comment]
This has been updated and is in release 0.44a.  I recommend existing users update the field in the GUI.  New users will have the right default id.
